import Head from "next/head";
import Navbar from "@components/Navbar";
import HeroPages from "./HeroPages";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Streamline Agency</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/pro.ico" />
      </Head>
      <Navbar />
      <HeroPages />
    </div>
  );
}
